noConsole: '&cThis command can only be executed by in-game players.'
noPermission: '&cNo permission.'
missingArgs: '&cMissing arguments.'
npcCreated: '&aCreated NPC %s'
alreadyExists: '&cAn NPC with that name already exists.'
npcDeleted: '&aDeleted NPC %s'
noNpcs: '&cThere are currently no NPCs, create one using /createnpc <name>.'
npcListElement: '&e%d# &a%s'
npcInfo: '&e%s &7| &a%s &7| &b%s %s'
distance: '(%dm away)'
diffWorld: '(In world %s)'
notFound: "&cCouldn't find an NPC near you."
notFoundName: "&cCouldn't find an NPC named %s"
alreadyRunning: '&cNPC %s is already executing an action.'
invalidNumber: '&c%s is not a valid number.'
invalidHand: '&c%s is not a valid hand.'
npcViewDistance: 60