messages:
  noconsole: '&cThis command can only be executed by in-game players.'
  nopermission: '&cNo permission.'
  missingargs: '&cMissing arguments.'
  npccreated: '&aCreated NPC %s'
  npcdeleted: '&aDeleted NPC %s'
  nonpcs: '&cThere are currently no NPCs, create one using /createnpc <name>.'
  npclistelement: '&e%d# &a%s'
  npcinfo: '&e%s &7| &a%s &7| &b%s'
  npcinfoconsole: '&e%s &7| &a%s'
  notfound: "&cCouldn't find an NPC near you."
  alreadyrunning: '&cNPC %s is already executing an action.'
  invalidnumber: '&c%s is not a valid number.'
  invalidhand: '&c%s is not a valid hand.'